### ISSUE TITLE
Database schema and CRUD for `Appointments`

### ISSUE THREAD

**Issue by moozeq** [moozeq/clinr#9]
**Description**

Create basic back-end part for `Appointments` which are conducted under specific `Study` (#7) in specific `Facility` (#4) by `User` with a `"doctor"` `Role` (#3) to register specific `Patient` (#5) visit in facility.

**Prerequisites**

- [x] #3 
- [x] #4 
- [ ] #5 
- [ ] #7 
- [ ] #8

**Acceptance criteria**

- [ ] Create database schema for `Appointment` class using [sequelize-typescript](https://github.com/sequelize/sequelize-typescript) with fields:
  - `date`
  - `type` - visit type, allowed values: `drugAdminitration` (drug administered during the visit), `checkup` (checkup for doctor to see if there are any adverse effects between drug administrations), `followup` (visit 1 month after completed study by patient), `survivalCheck` (visit 1 year after followup to register long-term effects)
  - `description`
  - `adverseEffects[]` - registered adverse effects based on the interview with the patient (#8)
  - `patient`
  - `doctor`
  - `facility`
- [ ] Add CRUD for `Appointment` but only accessible for authorized `Users` with `"doctor"` `Role`
- [ ] Add association one-to-one for `Appointment` and `Patient` (#5)
- [ ] Add association one-to-one for `Appointment` and `User`(doctor who conducted the visit)
- [ ] Add association one-to-one for `Appointment` and `Facility` (#4)
- [ ] Add association one-to-many for `Appointment` and `AdverseEffects` (#8)
